# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-18.04'

strategy:
  matrix:
    example_function1:
      function: example_function1
    example_function2:      
      function: example_function2
    example_with_logging:
      function: example_with_logging

container:
  image: cognite/function-action:v1

steps:
  - bash: |
        wget -qO ./yq https://github.com/mikefarah/yq/releases/download/v4.12.2/yq_linux_amd64
        chmod +x ./yq
    name: install_yq

  - bash: |
        FILE="$FUNCTION/function_config.yaml"
        if [ ! -f $FILE ]; then
            echo "Config: $FILE not supplied!"
        else
            ALLKEYS=$(./yq e "... comments=\"\" | keys" $FILE)
            for CONFIGURATION in $ALLKEYS
            do
              if [ "$CONFIGURATION" != "-" ]; then
                  VALUE=$(./yq e ".$CONFIGURATION" $FILE)
                  echo "##vso[task.setvariable variable=$CONFIGURATION;]:$VALUE"
              fi
            done
        fi
    name: config_param

  - script: |
      INPUT_FUNCTION_FOLDER=$FUNCTION
      INPUT_SCHEDULE_FILE=schedules/$(Build.SourceBranchName).yaml
      INPUT_FUNCTION_EXTERNAL_ID=$FUNCTION-$(Build.SourceBranchName)
      INPUT_FUNCTION_SECRETS=SECRETS_$FUNCTION_$(Build.SourceBranchName)
      INPUT_DEPLOYMENT_TENANT_ID=$DEPLOYMENT_TENANT_ID
      INPUT_DEPLOYMENT_CLIENT_ID=$DEPLOYMENT_CLIENT_ID
      INPUT_DEPLOYMENT_CLIENT_SECRET=$DEPLOY_$(Build.SourceBranchName)
      INPUT_SCHEDULES_TENANT_ID=$SCHEDULES_TENANT_ID
      INPUT_SCHEDULES_CLIENT_ID=$SCHEDULES_CLIENT_ID
      INPUT_SCHEDULES_CLIENT_SECRET=$SCHEDULES_$(Build.SourceBranchName)
      INPUT_CDF_PROJECT=$CDF_PROJECT
      INPUT_CDF_CLUSTER=$CDF_CLUSTER
      INPUT_OWNER=$OWNER
      INPUT_DESCRIPTION=$DESCRIPTION
      INPUT_FUNCTION_FILE=$FUNCTION_FILE
      INPUT_DATA_SET_ID=$DATA_SET_ID
      INPUT_COMMON_FOLDER=$COMMON_FOLDER
      INPUT_REMOVE_ONLY=$REMOVE_ONLY
      INPUT_CPU=$CPU
      INPUT_MEMORY=$MEMORY
      INPUT_ENV_VARS=$ENV_VARS
      INPUT_FUNCTION_DEPLOY_TIMEOUT=$FUNCTION_DEPLOY_TIMEOUT
      INPUT_POST_DEPLOY_CLEANUP=$POST_DEPLOY_CLEANUP
      python /app/index.py
    displayName: Deploy Functions to CDF
